Create a plist->bplist wrapper script + remove an old release notice reference
theos/theos pull request #636
Opened 2022-02-14 03:12 UTC by L1ghtmann

What does this implement/fix? Explain your changes.
---------------------------------------------------
Creates a plist->bplist wrapper script, adds support for plistutil (libplist-utils), and removes an old release notice reference (post-update).

Does this close any currently open issues?
------------------------------------------
Resolves #134 

Any relevant logs, error output, etc?
-------------------------------------
Nope.

Any other comments?
-------------------
While plutil was able to handle all of the xml formats I threw at it, plistutil was not. It failed to convert most non-standard xml formats including but not limited to NeXTStep and single line .plists as well as .strings. That being said, something is better than nothing, so this'll do for the time being. 

Where has this been tested?
---------------------------
**Operating System:** …

Linux (WSL) and iOS (Taurine and Unc0ver - 14.3)

**Platform:** …

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

2022-02-14 03:40 UTC, DHowett commented
If [`ply`](https://github.com/dhowett/go-plist/tree/main/cmd/ply) is available, it might be a reasonable alternative. It's fairly well cross-platform, though it being written in Go does limit its ease of installation somewhat.

Incidentally, I'd love to know what property lists plistutil couldn't deal with so I can make sure `ply` can :smile:

2022-02-14 04:00 UTC, kirb requested changes
Looks good, just had a few notes.

Also could you rename to convert_xml_plist.sh so it’s initially clearer what the script’s purpose is, and ensure the code style is consistent by converting spaces to tabs.

And, indeed, supporting ply would be a great idea. Totally forgot about it since #134 only mentions plistutil! Its interface is definitely far more intuitive than plistutil, and I haven’t seen it hit any issues parsing in my experience (it’s used by Packix to grab icons from apps/prefs bundles, so I’m somewhat confident 🙂). The script could look for it in between plutil and plistutil, and we can add an extra step to the Linux install instructions to install ply.

2022-02-14 20:52 UTC, L1ghtmann commented
> If [`ply`](https://github.com/dhowett/go-plist/tree/main/cmd/ply) is available, it might be a reasonable alternative. It's fairly well cross-platform, though it being written in Go does limit its ease of installation somewhat.
> 
> Incidentally, I'd love to know what property lists plistutil couldn't deal with so I can make sure `ply` can 😄

I installed ply and tested it against the same projects I was testing plistutil with and I gotta say, it is *damn* impressive. Awesome job! It worked perfectly just like plutil, so don't think there are any other formats required at the moment.

2022-02-14 20:52 UTC, L1ghtmann commented on bin/update-theos
> -exec bin/post-update
Gotcha. Reverted my change and simply updated the notice to link to the master branch's commit history instead of releases.

2022-02-14 20:54 UTC, L1ghtmann commented on bin/convert_xml.sh
> +            plutil -convert binary1 $i &> /dev/null
Yeah, it was a bit excessive with plistutil, but now that ply takes precedent that shouldn't be a problem. Removed the pipe to null.

2022-02-14 20:56 UTC, L1ghtmann commented on bin/convert_xml.sh
> +results_array=($results)
Added the quotes and the directory is just the theos staging dir, so it *should* be fine.

2022-02-14 23:24 UTC, kirb commented on bin/update-theos
> -exec bin/post-update
Good call :+1:

2022-10-30 03:53 UTC, kirb approved these changes

2022-10-30 04:03 UTC, kirb commented
Squashed and merged, thanks!

2022-10-30 04:03 UTC, closed without merging