Added .keep for lib/iphone/rootless
theos/theos pull request #725
Opened 2023-04-17 18:46 UTC by MrGcGamer

What does this implement/fix? Explain your changes.
---------------------------------------------------
This is just GitHub house-keeping `$THEOS/lib/iphone/rootless` already exists, after installation

Does this close any currently open issues?
------------------------------------------
Don't think so

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** …

**Platform:** …

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

2023-04-17 19:18 UTC, MrGcGamer commented
included in #712

2024-02-01 14:17 UTC, MrGcGamer commented
As #712 has been closed, without implementing this, I am reopening this PR.

2024-05-16 14:26 UTC, leptos-null commented on lib/iphone/rootless/.keep
> +
nit: this file is 1 byte (line break) instead of empty

2024-05-16 15:02 UTC, leptos-null requested changes
Small nit-pick for consistency with other `.keep` files in this repo.

This PR is important for `internal-library-stage_`/`internal-framework-stage_` to work correctly.

2024-05-16 16:33 UTC, leptos-null approved these changes
Thanks

2024-05-18 01:13 UTC, uroboro approved these changes

2024-05-20 04:00 UTC, leptos-null commented
#801 now creates this directory as needed.
I'm merging this PR as well so that the directory is easy to access.
Any number of schemes may exist, so I'm planning to include (via `.keep` files) `lib/{target}/{scheme}` directories in this repositories that have a mirrored directory in https://github.com/theos/lib

2024-05-20 04:00 UTC, merged