Avoid rate limits for the GitHub APIs
theos/theos pull request #831
Opened 2024-11-12 10:29 UTC by Lessica

What does this implement/fix? Explain your changes.
---------------------------------------------------
This pull request reduces occuring of `1 - api.github.com request failed` error.

Does this close any currently open issues?
------------------------------------------
No.

Any relevant logs, error output, etc?
-------------------------------------
No.

Any other comments?
-------------------
See [Make authenticated requests](https://docs.github.com/en/rest/using-the-rest-api/best-practices-for-using-the-rest-api?apiVersion=2022-11-28#make-authenticated-requests).  
The default primary rate limit of GitHub API is 60 requests per hour. That's not enough when you're sharing IP addresses with your roommate.

Where has this been tested?
---------------------------
**Operating System:** macOS 14.7.1 (23H222)

**Platform:** Any

**Target Platform:** Any

**Toolchain Version:** Any

**SDK Version:** Any

2024-11-12 15:06 UTC, PoomSmart approved these changes

2024-11-23 18:49 UTC, L1ghtmann requested changes
Thanks for this! One stylistic nitpick for consistency otherwise looks good

2024-11-23 18:49 UTC, L1ghtmann commented on bin/install-sdk
> +if [ ! -z "$GITHUB_TOKEN" ]; then
```suggestion
if ! [[ -z "$GITHUB_TOKEN" ]]; then
```

2024-11-26 14:20 UTC, L1ghtmann approved these changes
Thanks again!

2024-11-26 14:24 UTC, merged