Respect ZDOTDIR
theos/theos pull request #834
Opened 2024-12-30 02:06 UTC by RoadRoller01

What does this implement/fix? Explain your changes.
---------------------------------------------------
ZDOTDIR is the path to the user's zsh configuration, so it may not always be located in the home directory,
More information could be found in zsh man page,

Does this close any currently open issues?
------------------------------------------
No

Any relevant logs, error output, etc?
-------------------------------------
No

Any other comments?
-------------------
No

2024-12-30 12:54 UTC, PoomSmart approved these changes

2024-12-30 20:58 UTC, L1ghtmann requested changes
Thanks for this! Had two minor things that I believe were missed (?), but looks good otherwise. Manpage [ref](https://zsh.sourceforge.io/Doc/Release/Files.html#Files)

2024-12-30 20:58 UTC, L1ghtmann commented on bin/install-theos
>  		SHELL_ENV="$HOME/.zshenv"
```suggestion
		SHELL_ENV="$zdot/.zshenv"
```

2024-12-30 20:58 UTC, L1ghtmann commented on bin/install-theos
>  		SHELL_ENV="$HOME/.zprofile"
```suggestion
		SHELL_ENV="$zdot/.zprofile"
```

2024-12-30 23:18 UTC, RoadRoller01 commented
Oh i forget theos haha

2024-12-30 23:47 UTC, L1ghtmann approved these changes

2024-12-31 16:29 UTC, merged

2024-12-31 16:29 UTC, L1ghtmann commented
Thanks again!